/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.usac_delivery.usac_delivery.graficos.graficos_NormalUser;

import com.usac_delivery.usac_delivery.controladores.Controlador_Usuario;
import com.usac_delivery.usac_delivery.controladores.Controlador_targeta;
import com.usac_delivery.usac_delivery.graficos.g_menu;
import com.usac_delivery.usac_delivery.modelos.M_Usuario;
import com.usac_delivery.usac_delivery.modelos.M_targeta;

import javax.swing.*;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import java.text.ParseException;
import java.util.ArrayList;

/**
 *
 * @author Julio Lima
 */
public class g_manejadorTarjeta extends javax.swing.JFrame {

    /**
     * Creates new form g_manejadorTarjeta
     */
    static String idFacturin="";
    public g_manejadorTarjeta() {
        initComponents();

        idFacturin="";


        Controlador_targeta targeta = new Controlador_targeta();
        ArrayList<M_targeta> visualizadorTargeta = new ArrayList<>();

        visualizadorTargeta=targeta.getTargetasNombre(String.valueOf( Controlador_Usuario.usuarioLogeado.get(0).getP_id()));

        if(!visualizadorTargeta.isEmpty()){
            DefaultComboBoxModel<String> newModel = new DefaultComboBoxModel<>();
             String numero;
            for(M_targeta p:visualizadorTargeta){
                numero= p.getD_codigo();
                numero = numero.substring(numero.length() - 4);
                numero = "XXXXXXXX"+numero;
                newModel.addElement("Nombre:"+p.getD_nombre()+" "+"Numero"+numero);

            }
            jComboBox1.setModel(newModel);

        }



        MaskFormatter formatter = null;
        try {
            formatter = new MaskFormatter("##/##");
            formatter.setPlaceholderCharacter('_');
            formatter.setValidCharacters("0123456789");
            formatter.setAllowsInvalid(false);
            formatter.setOverwriteMode(true);
        } catch (ParseException ex) {
            System.err.println("Error al crear el MaskFormatter: " + ex.getMessage());
        }




        DefaultFormatterFactory factory = new DefaultFormatterFactory(formatter);

        JFormattedTextField textField = new JFormattedTextField();
        textField.setFormatterFactory(factory);

        jFormattedTextField1.setFormatterFactory(factory);

        if(!jTextField1.getText().isEmpty() && !jFormattedTextField1.getText().contains("_") && !jFormattedTextField2.getText().isEmpty() ){
            jButton1.setEnabled(true);
            jButton2.setEnabled(true);


        }else{
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);

        }


        //dpi

        MaskFormatter formatter2 = null;
        try {
            formatter2 = new MaskFormatter("############");
            formatter2.setPlaceholderCharacter('_');
            formatter2.setValidCharacters("0123456789");
            formatter2.setAllowsInvalid(false);
            formatter2.setOverwriteMode(true);
        } catch (ParseException ex) {
            System.err.println("Error al crear el MaskFormatter: " + ex.getMessage());
        }

        DefaultFormatterFactory factory2 = new DefaultFormatterFactory(formatter2);




        jFormattedTextField2.setFormatterFactory(factory2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel7.setText("jLabel7");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel7)
                .addContainerGap(293, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(278, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manejador");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Tarjeta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("tarjetas");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre de tarjeta");

        jFormattedTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFormattedTextField1KeyReleased(evt);
            }
        });

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jLabel5.setText("fecha");

        jLabel6.setText("Numero");

        jFormattedTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFormattedTextField2KeyReleased(evt);
            }
        });

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jFormattedTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                                        .addGap(97, 97, 97)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton3)
                .addGap(5, 5, 5)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Controlador_targeta targeta = new Controlador_targeta();
        ArrayList<M_targeta> visualizadorTargeta = new ArrayList<>();
        ArrayList<M_Usuario> user = new ArrayList<>();


        user= Controlador_Usuario.getArrayUserLogeado();
        String Exito;
        Exito=Controlador_targeta.RegistrarTargeta(jFormattedTextField2.getText(),jTextField1.getText(),jFormattedTextField1.getText(),String.valueOf(user.get(0).getP_id()) );

        if(Exito=="true"){

String numero;

            visualizadorTargeta=targeta.getTargetasNombre(String.valueOf( Controlador_Usuario.usuarioLogeado.get(0).getP_id()));


                DefaultComboBoxModel<String> newModel = new DefaultComboBoxModel<>();

                for(M_targeta p:visualizadorTargeta){
                    numero= p.getD_codigo();
                    numero = numero.substring(numero.length() - 4);
                    numero = "XXXXXXXX"+numero;
                    newModel.addElement("Nombre: "+p.getD_nombre()+"/ "+"Numero: "+ numero);

                }
                jComboBox1.setModel(newModel);
                jComboBox1.setSelectedItem(newModel.getSize()-1);


        }else{
            jLabel7.setText(Exito);

            jDialog1.setVisible(true);
            jDialog1.setSize(330,100);
            jDialog1.setLocation(500,100);

            System.out.println(Exito);        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        g_menu irMenu = new g_menu();
        this.dispose();

        irMenu.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        Controlador_targeta targeta = new Controlador_targeta();
        ArrayList<M_targeta> visualizadorTargeta = new ArrayList<>();

        visualizadorTargeta=targeta.getTargetasNombre(String.valueOf( Controlador_Usuario.usuarioLogeado.get(0).getP_id()));

        if(!visualizadorTargeta.isEmpty()){
            jTextField1.setText(visualizadorTargeta.get(jComboBox1.getSelectedIndex()).getD_nombre());
            jFormattedTextField1.setText(visualizadorTargeta.get(jComboBox1.getSelectedIndex()).getFecha_de_vencimiento());
            jFormattedTextField2.setText(visualizadorTargeta.get(jComboBox1.getSelectedIndex()).getD_codigo());

        }

        if(!jTextField1.getText().isEmpty() && !jFormattedTextField1.getText().contains("_") && !jFormattedTextField2.getText().contains("_") ){
            jButton1.setEnabled(true);
            jButton2.setEnabled(true);


        }else{
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);

        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Controlador_targeta targeta = new Controlador_targeta();
        ArrayList<M_targeta> visualizadorTargeta = new ArrayList<>();
        ArrayList<M_Usuario> user = new ArrayList<>();
        int id = jComboBox1.getSelectedIndex();

        user= Controlador_Usuario.getArrayUserLogeado();

        visualizadorTargeta=targeta.getTargetasNombre(String.valueOf(user.get(0).getP_id()));
        System.out.println(visualizadorTargeta.get(jComboBox1.getSelectedIndex()).getIdTargeta());

        String Exito;
        Exito=Controlador_targeta.EditarTargeta(jFormattedTextField2.getText(),jTextField1.getText(),jFormattedTextField1.getText(),String.valueOf(user.get(0).getP_id()),visualizadorTargeta.get(jComboBox1.getSelectedIndex()).getIdTargeta() );

        if(Exito=="true"){


            String numero;

            visualizadorTargeta=targeta.getTargetasNombre(String.valueOf( Controlador_Usuario.usuarioLogeado.get(0).getP_id()));


            DefaultComboBoxModel<String> newModel = new DefaultComboBoxModel<>();

            for(M_targeta p:visualizadorTargeta){
                numero= p.getD_codigo();
                numero = numero.substring(numero.length() - 4);
                numero = "XXXXXXXX"+numero;
                newModel.addElement("Nombre: "+p.getD_nombre()+"/ "+"Numero: "+ numero);

            }
            jComboBox1.setModel(newModel);
            jComboBox1.setSelectedItem(id);

        }else{
            jLabel7.setText(Exito);

            jDialog1.setVisible(true);
            jDialog1.setSize(330,100);
            jDialog1.setLocation(500,100);

            System.out.println(Exito);        }

        if(!jTextField1.getText().isEmpty() && !jFormattedTextField1.getText().contains("_") && !jFormattedTextField2.getText().contains("_") ){
            jButton1.setEnabled(true);
            jButton2.setEnabled(true);


        }else{
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        if(!jTextField1.getText().isEmpty() && !jFormattedTextField1.getText().contains("_") && !jFormattedTextField2.getText().contains("_") ){
            jButton1.setEnabled(true);
            jButton2.setEnabled(true);


        }else{
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);

        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jFormattedTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField1KeyReleased
        // TODO add your handling code here:
        if(!jTextField1.getText().isEmpty() && !jFormattedTextField1.getText().contains("_") && !jFormattedTextField2.getText().contains("_") ){
            jButton1.setEnabled(true);
            jButton2.setEnabled(true);


        }else{
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);

        }
    }//GEN-LAST:event_jFormattedTextField1KeyReleased

    private void jFormattedTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField2KeyReleased
        // TODO add your handling code here:
        if(!jTextField1.getText().isEmpty() && !jFormattedTextField1.getText().contains("_") && !jFormattedTextField2.getText().contains("_") ){
            jButton1.setEnabled(true);
            jButton2.setEnabled(true);


        }else{
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);

        }
    }//GEN-LAST:event_jFormattedTextField2KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(g_manejadorTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(g_manejadorTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(g_manejadorTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(g_manejadorTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new g_manejadorTarjeta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
