/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.usac_delivery.usac_delivery.graficos.graficos_NormalUser;

import com.usac_delivery.usac_delivery.controladores.Controlador_DatosEnvio;
import com.usac_delivery.usac_delivery.controladores.Controlador_Usuario;
import com.usac_delivery.usac_delivery.graficos.g_menu;
import com.usac_delivery.usac_delivery.graficos.graficos_NormalUser.comprar.g_verYconseguir;
import com.usac_delivery.usac_delivery.modelos.M_DatosEnvio;
import com.usac_delivery.usac_delivery.modelos.M_Usuario;
import com.usac_delivery.usac_delivery.modelos.M_departamento;

import javax.swing.*;
import java.util.ArrayList;

/**
 *
 * @author Julio Lima
 */
public class g_VermisEnvios extends javax.swing.JFrame {

    /**
     * Creates new form g_VermisEnvios
     */
    public g_VermisEnvios() {
        initComponents();
        Controlador_DatosEnvio dE = new Controlador_DatosEnvio();
        Controlador_Usuario user = new Controlador_Usuario();

        ArrayList<M_Usuario> usuario = new ArrayList<>();

        usuario = user.getArrayUserLogeado();



        if(!dE.getEnviActual().isEmpty()){
            dE.setAdiosEnviActual();

        }


        ArrayList<M_DatosEnvio> visualizador = new ArrayList<>();
        visualizador=dE.getMisenvios(""+usuario.get(0).getP_id());
        DefaultComboBoxModel<String> newModelDO = new DefaultComboBoxModel<>();

        if(visualizador.isEmpty()){
            newModelDO.addElement("");

            jComboBox1.setModel(newModelDO);
            jButton2.setEnabled(false);

        }else {
            for(M_DatosEnvio p:visualizador){

                newModelDO.addElement(" Codigo:"+p.getCodigoGuia()+"  Emisor:"+p.getDestinatarioName()+"  fecha:"+p.getFechaEnvio());
            }
            jComboBox1.setModel(newModelDO);
        }





    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mis envios");

        jButton1.setText("regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ver envio");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jButton2)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(29, 29, 29)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton2)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Controlador_DatosEnvio envio = new Controlador_DatosEnvio();
        Controlador_DatosEnvio dE = new Controlador_DatosEnvio();
        Controlador_Usuario user = new Controlador_Usuario();

        ArrayList<M_Usuario> usuario = new ArrayList<>();

        usuario = user.getArrayUserLogeado();


        ArrayList<M_DatosEnvio> visualizador = new ArrayList<>();
        visualizador=dE.getMisenvios(""+usuario.get(0).getP_id());

        envio.setEnviActual(visualizador.get(jComboBox1.getSelectedIndex()));

        g_verYconseguir vyc = new g_verYconseguir();
        this.dispose();
        vyc.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        Controlador_DatosEnvio dE = new Controlador_DatosEnvio();
        Controlador_Usuario user = new Controlador_Usuario();

        ArrayList<M_Usuario> usuario = new ArrayList<>();

        usuario = user.getArrayUserLogeado();


        ArrayList<M_DatosEnvio> visualizador = new ArrayList<>();
        visualizador=dE.getEnviActual();


        if(!visualizador.isEmpty()){
            dE.setAdiosEnviActual();

        }

        g_menu irMenu = new g_menu();
        this.dispose();

        irMenu.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(g_VermisEnvios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(g_VermisEnvios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(g_VermisEnvios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(g_VermisEnvios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new g_VermisEnvios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
